---
title: |
  <center> Incomplete Data Analysis </center>
  <center> Assignment 2 </center>
author: "Jay Huang"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

Question2(b)

```{r, include = TRUE, message = FALSE, tidy = TRUE, fig.align = 'center'}
load("dataex2.Rdata")
X = dataex2$X
R = dataex2$R
log_like_leftNorm = function(y, mu){
  n = length(y)
  log_like = 0
  for (i in 1:n) {
    log_i = (R[i] * dnorm(y[i], mean = mu, sd = 1.5, log = TRUE)
             + (1 - R[i]) * pnorm(y[i], mean = mu, sd = 1.5, log = TRUE))
    log_like = log_like + log_i
  }
  return(log_like)
}

mleoptim = optim(par = c(0), fn = log_like_leftNorm, y = X, 
                 control = list("fnscale"=-1), hessian = TRUE)
mleoptim
```



Question4:

```{r, include = TRUE, message = FALSE, tidy = TRUE, fig.align = 'center'}
load("dataex4.Rdata")
em_dataex4 = function(dataex, beta0, eps){
  x = dataex[,1]
  y = dataex[,2]
  ind = which(is.na(y))
  y_obs = y[-ind]
  y_mis = y[ind]
  n = length(y)
  m = length(y_obs)
  diff = 1
  beta = beta0
  
  while(diff>eps){
    beta.old = beta
    
    Q_obj = function(param){
      beta_0 = param[1]
      beta_1 = param[2]
      
      obj_1 = sum(-log(1+exp(beta_0+beta_1*x)))
      obj_2 = sum(y_obs*(beta_0+beta_1*x[-ind]))
      obj_3 = 0
      for (i in 1:(n-m)) {
        indi = ind[i]
        temp1 = beta.old[1] + beta.old[2]*x[indi]
        temp2 = exp(temp1)/(1 + exp(temp1))
        temp3 = temp2 * (beta_0+beta_1*x[indi])
        obj_3 = obj_3 + temp3
      }
      
      obj = obj_1 + obj_2 + obj_3
    }
    
    optim_it = optim(par = c(beta.old[1], beta.old[2]), fn = Q_obj, control = list("fnscale"=-1), hessian = TRUE)
    beta = optim_it$par
    
    diff = sum(abs(beta - beta.old))
  }
  return(beta)
}

em_dataex4(dataex4, c(0,0), 0.0001)

```




Question5:

```{r, include = TRUE, message = FALSE, tidy = TRUE, fig.align = 'center'}
load("dataex5.Rdata")

f_LogNorm = function(y, mu, sigma_squ){
  v = 1/y * dnorm(log(y), mean = mu, sd = sigma_squ^(0.5), log = FALSE)
  return(v)
}

f_Exp = function(y, lamda){
  return(dexp(y, lamda))
}

em.dataex5 = function(y, theta0, eps){
  n = length(y)
  theta = theta0
  
  p = theta[1]
  mu = theta[2]
  sigma_squ = theta[3]
  lamda = theta[4]
  
  diff = 1
  
  while (diff > eps) {
    theta.old = theta
    
    #E-step
    ptilde1 = p * f_LogNorm(y, mu, sigma_squ)
    ptilde2 = (1 - p) * dexp(y, lamda)
    ptilde = ptilde1/(ptilde1 + ptilde2)
    
    #M-setp
    p = mean(ptilde)
    mu = sum(ptilde * log(y))/sum(ptilde)
    sigma_squ = sum(ptilde * (log(y)-mu)^2) / sum(ptilde)
    lamda = sum(1-ptilde) / sum((1-ptilde)*y)
    
    theta = c(p, mu, sigma_squ, lamda)
    diff = sum(abs(theta - theta.old))
  }
  return(theta)
}

res = em.dataex5(dataex5, c(0.1,1,0.5^2,2), 0.0001)
p = res[1]
mu = res[2]
sigma_square = res[3]
lamda = res[4]

p; mu; sigma_square; lamda

hist(dataex5, main = "question 5", freq = F)
curve(p*f_LogNorm(x, mu, sigma_square) + (1-p)*f_Exp(x, lamda), add = TRUE, col = "blue2")
```


